imports:
  - { resource: "services.yaml" }
  - { resource: "monsieurbiz_search.yaml" }
  - { resource: "sylius/ui.yaml" }
  - { resource: "sylius/fixtures.yaml" }
  - { resource: "sylius/grids.yaml" }
  - { resource: "monsieurbiz/settings.yaml" }
  - { resource: "messenger.yaml" }

framework:
  assets:
    packages:
      monsieurbiz.sylius.search:
        json_manifest_path: '%kernel.project_dir%/public/bundles/monsieurbizsyliussearchplugin/manifest.json'
