name: Security

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 * * 0'

jobs:

  security:

    name: Security check (PHP ${{ matrix.php }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [ '8.0', '8.1', '8.2' ]

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Set project php-version
        run: |
          echo "${{ matrix.php }}" > .php-version

      - uses: actions/cache@v1
        id: cache-composer
        with:
          path: /home/runner/.composer/cache
          key: composer2-php:${{ matrix.php }}-${{ github.sha }}
          restore-keys: composer2-php:${{ matrix.php }}-

      - run: mkdir -p /home/runner/{.composer/cache,.config/composer}

      - name: Composer Github Auth
        run: composer config -g github-oauth.github.com ${{ github.token }}

      - uses: actions/checkout@v2

      - name: Install PHP dependencies
        run: composer update --prefer-dist

      - uses: symfonycorp/security-checker-action@v3
